# This is a basic workflow to help you get started with Actions

name: Generate Terraform Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate-readme:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # repository-projects: write
      # actions: write
      # checks: write
      # deployments: write
      # id-token: write


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # Runs a single command using the runners shell
      - name: Generate Terraform Docs
        run: echo Generate Terraform Docs

      # Action to generate Terraform documentation
      - name: Install Terraform Docs
        uses: terraform-docs/gh-actions@v1.2.2
        with:
          working_dir: .  # Use the current directory (adjust if needed)
          output-file: README.md  # Update the README file with generated docs
          output-method: inject  # Inject the documentation into the README
          git-push: "true"
        env:
          GH_TOKEN: ${{ secrets.README_TOKEN }}
