name: Create Release Tag

on:
  push:
    branches:
      - main

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up GitHub CLI
      - name: Install GitHub CLI
        uses: actions/setup-gh-cli@v2

      # Determine the next version (You could add logic to check the current version)
      - name: Get version from changelog
        id: changelog
        run: |
          VERSION=$(grep -m 1 -oP '(?<=## \[v)[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      # Create a tag and push it
      - name: Create Git tag
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      # Create a GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: "v${{ env.VERSION }}"
          body: |
            Release v${{ env.VERSION }} - $(date +"%Y-%m-%d")
        env:
          GITHUB_TOKEN: ${{ secrets.MODULE_TOKEN }}
